---
settings:
  name: SaaS Backup For Partner Central
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Centro de partners
    entries:
    - title: Documentación de NetApp SaaS Backup Partner Central
      url: "/index.html"
    - title: Notas de la versión
      entries:
      - title: Nuevas funciones y actualizaciones
        url: "/partnercentral_reference_new.html"
      - title: Problemas y limitaciones conocidos
        url: "/partnercentral_reference_limitations.html"
    - title: Regístrese en Partner Central
      url: "/partnercentral_task_register.html"
    - title: Añadir y gestionar clientes
      url: "/partnercentral_task_add_and_manage_customers.html"
    - title: Supervisar los trabajos del cliente
      url: "/partnercentral_task_monitor.html"
    - title: Generar informes
      url: "/partnercentral_task_generate_reports.html"
    - title: Gestionar configuración
      entries:
      - title: Gestionar notificaciones
        url: "/partnercentral_task_manage_notifications.html"
      - title: Gestionar roles
        url: "/partnercentral_task_manage_roles.html"
      - title: Administrar claves
        url: "/partnercentral_task_manage_keys.html"
    - title: Estadísticas
      url: "/partnercentral_reference_statistics.html"
    - title: Dónde encontrar ayuda y información
      url: "/partnercentral_reference_get_help_find_info.html"
